# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68b452edd20167e64dca21d2f1482bed1b1e217fed1d091d2dae07663ed8b1b6304840723d96826bab57fae115c188381293de720335fad0bf0acccc7b443083

test:
  secret_key_base: 5af6c83c1919b488a6b4a5dbdce43dcf96a420e1b1320535810c6867a325d7cf42c8645f4ad14edfe732dd268ff7c9e512ca271343c7d73371e6ebcf98887a02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
